package me.peter.graphexplorer

import scala.meta.internal.semanticdb._
import java.nio.file.{Files, Path}
import scala.jdk.CollectionConverters._

object GraphLoader {

  /** Load a call graph from all .semanticdb files found under `semanticdbRoot`. */
  def load(semanticdbRoot: Path): LoadedGraph = {
    val files = Files
      .walk(semanticdbRoot)
      .iterator()
      .asScala
      .filter(_.toString.endsWith(".semanticdb"))
      .toList

    if (files.isEmpty) {
      System.err.println(s"[graph-explorer] WARNING: no .semanticdb files found under $semanticdbRoot")
      System.err.println(s"[graph-explorer] Run 'compile' first.")
      return LoadedGraph.empty
    }

    val outB  = collection.mutable.Map.empty[String, collection.mutable.Set[String]]
    val inB   = collection.mutable.Map.empty[String, collection.mutable.Set[String]]
    val metaB = collection.mutable.Map.empty[String, NodeMeta]

    files.foreach { path =>
      try processFile(path, outB, inB, metaB)
      catch {
        case e: Exception =>
          System.err.println(s"[graph-explorer] WARNING: failed to parse $path: ${e.getMessage}")
      }
    }

    if (outB.isEmpty) {
      System.err.println(
        s"[graph-explorer] WARNING: graph is empty after loading ${files.size} files. " +
          "SemanticDB may not contain method-level call information for this project."
      )
    }

    LoadedGraph(
      out  = outB.view.mapValues(_.toSet).toMap,
      in   = inB.view.mapValues(_.toSet).toMap,
      meta = metaB.toMap,
    )
  }

  private def processFile(
    path: Path,
    out:  collection.mutable.Map[String, collection.mutable.Set[String]],
    in:   collection.mutable.Map[String, collection.mutable.Set[String]],
    meta: collection.mutable.Map[String, NodeMeta],
  ): Unit = {
    val bytes = Files.readAllBytes(path)
    val docs  = TextDocuments.parseFrom(bytes)

    docs.documents.foreach { doc =>
      // symbol → kind (method, field, class, ...)
      val kindOf: Map[String, SymbolInformation.Kind] =
        doc.symbols.map(s => s.symbol -> s.kind).toMap

      // symbol → displayName (for meta)
      val displayNameOf: Map[String, String] =
        doc.symbols.map(s => s.symbol -> s.displayName).toMap

      // Method DEFINITION occurrences in this file, sorted by start line
      val methodDefs: Vector[(String, Int)] =
        doc.occurrences
          .filter { occ =>
            occ.role == SymbolOccurrence.Role.DEFINITION &&
            occ.range.isDefined &&
            !isSynthetic(occ.symbol) &&
            kindOf.get(occ.symbol).contains(SymbolInformation.Kind.METHOD)
          }
          .map(occ => occ.symbol -> occ.range.get.startLine)
          .toVector
          .sortBy(_._2)

      // Populate meta for all method defs in this file
      methodDefs.foreach { case (sym, line) =>
        if (!meta.contains(sym)) {
          meta(sym) = NodeMeta(
            file        = doc.uri,
            startLine   = line,
            displayName = displayNameOf.getOrElse(sym, sym),
          )
        }
      }

      if (methodDefs.isEmpty) return

      // For a given line, find the innermost enclosing method (latest start <= line)
      def callerAt(line: Int): Option[String] =
        methodDefs.takeWhile(_._2 <= line).lastOption.map(_._1)

      // Method REFERENCE occurrences — these are call sites
      doc.occurrences
        .filter { occ =>
          occ.role == SymbolOccurrence.Role.REFERENCE &&
          occ.range.isDefined &&
          !isSynthetic(occ.symbol) &&
          kindOf.get(occ.symbol).contains(SymbolInformation.Kind.METHOD)
        }
        .foreach { occ =>
          val callee = occ.symbol
          callerAt(occ.range.get.startLine).foreach { caller =>
            if (caller != callee) {
              out.getOrElseUpdate(caller, collection.mutable.Set.empty) += callee
              in.getOrElseUpdate(callee, collection.mutable.Set.empty) += caller
            }
          }
        }
    }
  }

  /** Synthetic/anonymous symbols generated by the compiler — not useful as graph nodes. */
  private def isSynthetic(symbol: String): Boolean =
    symbol.startsWith("local") || symbol.isEmpty
}
